# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LentaNews',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('pub_date', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['category', '-pub_date'],
            },
        ),
    ]
